

class RandomGenerator {
	constructor(min, max) {
		//takes in the minimum and maximum values
		//if they are not defined, it sets the minimum to 1, and the max to 10
		//makes storage for the random number
		if (min == undefined) {
			this.min = 1
		} else {
			this.min = min
		}
		if (max == undefined) {
			this.max = 1
		} else {
			this.max = max
		}
		this.range = this.getRange();
		this.storeNumber = this.getNum();
	}
	generate() {
		//make a random value between the minimum and maximum values
		//and store the number into the storage from the constructor
		return Math.ceil(Math.random() * (this.max - this.min) + this.min)
	}
	getRange() {
		//return an object with min and max, min being the minimum value for the generator, max being the maximum value
		//returns a basic object literal
		return { min: this.min, max: this.max }
	}
	getNum() {
		//return the random number that was generated by generate()
		return this.generate()
	}
}